openapi: 3.0.0
info:
  title: Content  App
  description: Service for content delivery.
  license:
    name: Eclipse Public License - v 1.0
    url: https://www.eclipse.org/legal/epl-v10.html
  version: 1.0.0
servers:
- url: http://localhost:{port}
  description: Simple Open Liberty.
  variables:
    port:
      default: "9120"
      description: Server HTTP port.
